const { defaultEventBus } = require('./LocalEventBus');

class EventPersister {
  /**
   * @param {import('../persistence/interfaces/IEventRepository')} eventRepository 
   */
  constructor(eventRepository) {
    this.eventRepository = eventRepository;
  }

  start() {
    this._handler = async (event) => {
      // Prevent infinite loop: do not persist events generated by the EventRepository itself saving an event
      if (event.sourceComponent === 'EventRepository') return;
      try {
        await this.eventRepository.saveEvent(event);
      } catch (err) {
        console.error(`[EventPersister] Failed to persist event ${event.eventId}:`, err);
      }
    };
    // Subscribe to all events
    defaultEventBus.subscribe('*', this._handler);
    console.log('[EventPersister] Started listening to event bus for persistence.');
  }

  stop() {
    if (this._handler) {
      defaultEventBus.unsubscribe('*', this._handler);
      this._handler = null;
    }
  }
}

module.exports = EventPersister;
