const fs = require('fs/promises');
const SecureFilesystem = require('./SecureFilesystem');
const SandboxExecutionResult = require('../models/SandboxExecutionResult');

class SecureArtifactReader {
  /**
   * Reads execution artifacts from a workspace securely.
   * @param {string} workspacePath 
   * @param {object} options
   * @returns {Promise<SandboxExecutionResult>}
   */
  static async readArtifacts(workspacePath, options = {}) {
    const maxReportSizeBytes = options.maxReportSizeBytes || 10 * 1024 * 1024; // 10MB
    const maxLogSizeBytes = options.maxLogSizeBytes || 5 * 1024 * 1024; // 5MB
    const maxExitSizeBytes = 100 * 1024; // 100KB

    const artifactsDir = SecureFilesystem.resolveSecurePath(workspacePath, 'artifacts');
    let report = null;
    let logs = [];
    let metadata = {};
    let exitCode = 0;
    let error = null;

    // Securely read report.json
    try {
      const reportPath = SecureFilesystem.resolveSecurePath(artifactsDir, 'report.json');
      const data = await this._safeReadFile(reportPath, maxReportSizeBytes);
      if (data) {
        report = JSON.parse(data);
        if (!report || typeof report !== 'object') {
          throw this._createError('ArtifactValidationFailed', 'Invalid report.json schema');
        }
      }
    } catch (e) {
      if (e.reason === 'ArtifactSizeExceeded' || e.reason === 'ArtifactValidationFailed') {
        throw e;
      }
      error = 'Failed to read report.json: ' + e.message;
    }

    // Securely read logs.json
    try {
      const logsPath = SecureFilesystem.resolveSecurePath(artifactsDir, 'logs.json');
      const data = await this._safeReadFile(logsPath, maxLogSizeBytes);
      if (data) {
        logs = JSON.parse(data);
      }
    } catch (e) {
      if (e.reason === 'ArtifactSizeExceeded' || e.reason === 'ArtifactValidationFailed') {
        throw e;
      }
    }

    // Securely read .secaudit-metadata.json (trusted, generated by host usually, but we still read safely)
    try {
      const metaPath = SecureFilesystem.resolveSecurePath(workspacePath, '.secaudit-metadata.json');
      const data = await this._safeReadFile(metaPath, maxExitSizeBytes);
      if (data) {
        metadata = JSON.parse(data);
      }
    } catch (e) {
      // Optional
    }

    // Securely read exit.json
    try {
      const exitPath = SecureFilesystem.resolveSecurePath(artifactsDir, 'exit.json');
      const data = await this._safeReadFile(exitPath, maxExitSizeBytes);
      if (data) {
        const exitData = JSON.parse(data);
        if (!exitData || typeof exitData !== 'object' || Array.isArray(exitData)) {
          throw this._createError('ArtifactValidationFailed', 'Invalid exit.json schema');
        }
        exitCode = exitData.exitCode || 0;
        
        // Map untrusted exit error to controlled string if present to prevent leakage
        if (exitData.error) {
          const rawError = String(exitData.error).toLowerCase();
          if (rawError.includes('oom') || rawError.includes('memory')) {
            error = 'MEMORY_LIMIT';
          } else if (rawError.includes('timeout')) {
            error = 'TIMEOUT';
          } else if (rawError.includes('disk') || rawError.includes('space')) {
            error = 'DISK_LIMIT';
          } else {
            error = 'GENERAL_FAILURE: ' + String(exitData.error).substring(0, 200); // Truncate and wrap
          }
        }
      }
    } catch (e) {
      if (e.reason === 'ArtifactSizeExceeded' || e.reason === 'ArtifactValidationFailed') {
        throw e;
      }
      // exit.json missing or failed to read might happen if sandbox killed hard
    }

    return new SandboxExecutionResult({
      report,
      logs,
      metadata,
      exitCode,
      error
    });
  }

  static async _safeReadFile(filePath, maxSize) {
    try {
      const stats = await fs.stat(filePath);
      if (!stats.isFile()) {
        throw this._createError('ArtifactValidationFailed', `Artifact is not a regular file: ${filePath}`);
      }
      if (stats.size > maxSize) {
        throw this._createError('ArtifactSizeExceeded', `Artifact exceeds maximum allowed size of ${maxSize} bytes: ${filePath}`);
      }
      return await fs.readFile(filePath, 'utf8');
    } catch (err) {
      if (err.code === 'ENOENT') {
        return null;
      }
      throw err; // Propagate validation/size errors
    }
  }

  static _createError(reason, message) {
    const err = new Error(message);
    err.reason = reason;
    return err;
  }
}

module.exports = SecureArtifactReader;
